### ISSUE TITLE
when start playing immediately press device back button when stop and destroyplayer the spotify also  song is running even close the app.  If song is played after 30 seconds press device back button no issues

### ISSUE THREAD

**Issue by adarshakshetty** [spotify/android-sdk#165] opened 2015-11-20 11:57 UTC
when start playing immediately press device back button when stop and destroyplayer the spotify also  song is running even close the app.  If song is played after 30 seconds press device back button no issues

**Comment by kaaes** [comment] 2016-02-05 13:05
I'm closing this issue because it's not clear from the description what the actual problem is. Sounds however like it's caused by the app code, not the library.

**Closed by kaaes** 2016-02-05 13:05 UTC
