### ISSUE TITLE
Login issue when spotify app is installed but not logged in

### ISSUE THREAD

**Issue by dimaag** [spotify/android-sdk#205] opened 2016-03-07 19:23 UTC
I am using the beta12 sdk. The loginactivity works fine when the  spotify app is logged in. 
But if the user is logged out of the Spotify app and my app tries to initiate login activity, the login activity fails to open and generates a "NOT_LOGGED_IN" Auth Error.
Since the spotify app is logged out, shouldnt the login activity open its normal window to ask the user to input the login credentials?

**Comment by roberttaylor426** [comment] 2016-03-30 08:21
Duplicate of #175.

**Comment by middebugger** [comment] 2016-04-14 13:28
I facing the same problem

**Comment by d-kunin** [comment] 2016-09-02 15:58
closing dupe

**Closed by d-kunin** 2016-09-02 15:58 UTC
Labels: auth
