### ISSUE TITLE
Player does no longer play back tracks after inactivity

### ISSUE THREAD

**Issue by mrmaffen** [spotify/android-sdk#191] opened 2016-01-29 16:44 UTC
I have noticed that after coming back to my device after a few hours of inactivity, the Player object is no longer able to play back any track. I have been able to both look at the complete log output and debug the app directly and everything seems to work fine in my code, except that the Player doesn't output any audio.
In the log I can see that the Spotify SDK has reported several "temporary errors" while I was not using my device. Meaning it has called the onTemporaryError() callback. Unfortunately this really does not help at all because there is no Throwable object or error message String included in the onTemporaryError() callback (Please fix. Errors without any kind of information are useless)
When debugging the App directly I was able to see that the problem doesn't seem to be caused by my wrapper code.
After killing my App and recreating the Player object everything went back to normal and I was able to play back tracks as usual.

My current workaround is to always re-initialize the Player object. I'm removing all callbacks, calling pause() and then calling Spotify.getPlayer(...) again. This does seem to help for now.

The device I was able to reproduce the issue on was a Nexus 5 running 6.0.1. I'm using beta11 of the Spotify Android SDK.

**Comment by mrmaffen** [comment] 2016-02-01 04:53
The bug just happened again despite my crude workaround :/

**Comment by kaaes** [comment] 2016-02-05 13:00
I'll close this issue as it's a duplicate of #183 Let's track it there

**Closed by kaaes** 2016-02-05 13:00 UTC
Labels: bug, duplicate

**Comment by mrmaffen** [comment] 2016-02-05 14:29
I don't think it is a duplicate. There is no crash happening for me. The player object just stops outputing audio.
