### ISSUE TITLE
Refreshing Token Issue

### ISSUE THREAD

**Issue by HwanChoi** [spotify/android-sdk#408] opened 2018-03-30 08:20 UTC
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
how to refresh token to use my account in android SDK?
It is working for a hour however there is no method to refresh available token from Spotify server.
yes I have searched some closed issue and I have found using Back-End Service.
however I don't have experience about web server!
Please support android SDK. if there is a problem to support this issue!
let me know how can I support this function in Android device?
Thank you!

### Versions
Android Version over SDK > 22

### Severity
Major

## Steps to Reproduce
1. Step by step instructions on how to reproduce this bug.
2. The more detailed your list of instructions, the easier it is for the developer to track down the problem!

### Actual behaviour
Describe what happens when you perform the steps above.

### Expected behaviour
Describe what you expected to happen when performing the steps above.

## Logs
Please include any relevant log output that might assist in tracking down the problem.

**Comment by maracuja-juice** [comment] 2018-04-04 10:56
You need a backend because this Flow needs the Secret Key. This will probably help you: https://github.com/spotify/web-api-auth-examples

**Comment by bih** [comment] 2018-04-04 11:04
Hey!

The **highly recommended** option here is to have your own server backend, and deal with access and refresh tokens there. You should never have your Client Secret inside of your application, ever.

For your convenience, here's some material / tools to help you:
- [spotify/web-api-auth-examples](https://github.com/spotify/web-api-auth-examples) (if you'd like to build your own implementation)
- [bih/spotify-token-swap-service](https://github.com/bih/spotify-token-swap-service) (a pre-built implementation with one-click deployment).

Let me know if you have any questions. I'll close this issue as it is a duplicate of #192, #259, #260, #72, and #10.

**Closed by bih** 2018-04-04 11:04 UTC

**Comment by bih** [comment] 2018-04-04 13:08
@maracuja-juice If you're talking about the Spotify Token Swap service, you can manually send HTTP requests using a library such as [Fuel](https://github.com/kittinunf/Fuel) and just collect the access token. There's some interesting articles [on the internet](https://medium.com/@brianhans/spotify-ios-sdk-authentication-b2c35cd4affb) you can check too.

If you want to read more, there's a [full guide](https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/) on how authentication works with the Spotify API. It's built according to the [OAuth2](https://oauth.net/2/) specification, so you can read more about why you'd want to use authorization code flow vs implicit grant and others too 🙂

**Comment by maracuja-juice** [comment] 2018-04-04 13:33
@bih Okay so I just need to do it manually, that's all I wanted to know. Thanks.

**Comment by maracuja-juice** [comment] 2018-04-04 19:16
@bih Had a look at that article: Do you maybe know of something like it for android? (this is the android-sdk after all)
I'm interested in how to handle the authentication flow with the WebView / Spotify app exactly.
