### ISSUE TITLE
Begin tutorial for android SDK not working for me

### ISSUE THREAD

**Issue by JoseGeorges8** [spotify/android-sdk#387] opened 2017-11-16 17:11 UTC
Hello,

I do not know if this is the place to ask for help but in the comments of the tutorial it sent me to this page so well..

I did everything the tutorial told me to do, yet when I run my activity nothing seems to happen, the logs are not happening and nothing is being prompted.

this is my android Manifest:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.josegeorges.musicratingapp">

    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".LoginoutActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".AppActivity" />
        <activity android:name=".SignupActivity"></activity>

        
        <activity
            android:name="com.spotify.sdk.android.authentication.LoginActivity"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
    </application>

</manifest>`

This is my build.gradle:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.josegeorges.musicratingapp"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.spotify.android:auth:1.0.0-alpha'
    compile 'com.spotify.sdk:spotify-player-24-noconnect-2.20b@aar'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
`

and finally, the app trying to do the run:

`
   package com.josegeorges.musicratingapp;

import android.content.Intent;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.spotify.sdk.android.authentication.AuthenticationClient;
import com.spotify.sdk.android.authentication.AuthenticationRequest;
import com.spotify.sdk.android.authentication.AuthenticationResponse;
import com.spotify.sdk.android.player.Config;
import com.spotify.sdk.android.player.ConnectionStateCallback;
import com.spotify.sdk.android.player.Error;
import com.spotify.sdk.android.player.Player;
import com.spotify.sdk.android.player.PlayerEvent;
import com.spotify.sdk.android.player.Spotify;
import com.spotify.sdk.android.player.SpotifyPlayer;

public class AppActivity extends AppCompatActivity implements SpotifyPlayer.NotificationCallback, ConnectionStateCallback{

    FragmentManager fm;

    //Spotify constants
    private static final String CLIENT_ID = "4dc5084aee1045a383a99141c29dc15a";
    private static final String REDIRECT_URI = "music-rating-app-login://callback";
    // Request code that will be used to verify if the result comes from correct activity
    // Can be any integer
    private static final int REQUEST_CODE = 1337;

    private Player mPlayer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_app);

        AuthenticationRequest.Builder builder = new AuthenticationRequest.Builder(CLIENT_ID,
                AuthenticationResponse.Type.TOKEN,
                REDIRECT_URI);
        builder.setScopes(new String[]{"user-read-private", "streaming"});
        AuthenticationRequest request = builder.build();

        AuthenticationClient.openLoginActivity(this, REQUEST_CODE, request);

//        fm = getSupportFragmentManager();
//        FragmentTransaction transaction = fm.beginTransaction();
//        transaction.replace(R.id.content, new MainFragment());
//        transaction.commit();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
        super.onActivityResult(requestCode, resultCode, intent);

        // Check if result comes from the correct activity
        if (requestCode == REQUEST_CODE) {
            AuthenticationResponse response = AuthenticationClient.getResponse(resultCode, intent);
            if (response.getType() == AuthenticationResponse.Type.TOKEN) {
                Config playerConfig = new Config(this, response.getAccessToken(), CLIENT_ID);
                Spotify.getPlayer(playerConfig, this, new SpotifyPlayer.InitializationObserver() {
                    @Override
                    public void onInitialized(SpotifyPlayer spotifyPlayer) {
                        mPlayer = spotifyPlayer;
                        mPlayer.addConnectionStateCallback(AppActivity.this);
                        mPlayer.addNotificationCallback(AppActivity.this);
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        Log.e("MainActivity", "Could not initialize player: " + throwable.getMessage());
                    }
                });
            }
        }
    }

    @Override
    protected void onDestroy() {
        Spotify.destroyPlayer(this);
        super.onDestroy();
    }

    @Override
    public void onPlaybackEvent(PlayerEvent playerEvent) {
        Log.d("MainActivity", "Playback event received: " + playerEvent.name());
        switch (playerEvent) {
            // Handle event type as necessary
            default:
                break;
        }
    }

    @Override
    public void onPlaybackError(Error error) {
        Log.d("MainActivity", "Playback error received: " + error.name());
        switch (error) {
            // Handle error type as necessary
            default:
                break;
        }
    }

    @Override
    public void onLoggedIn() {
        Log.d("MainActivity", "User logged in");

        mPlayer.playUri(null, "spotify:track:2TpxZ7JUBn3uw46aR7qd6V", 0, 0);
    }

    @Override
    public void onLoggedOut() {
        Log.d("MainActivity", "User logged out");
    }

    @Override
    public void onLoginFailed(Error error) {
        Log.d("MainActivity", "Login failed");
    }

    @Override
    public void onTemporaryError() {
        Log.d("MainActivity", "Temporary error occurred");
    }

    @Override
    public void onConnectionMessage(String message) {
        Log.d("MainActivity", "Received connection message: " + message);
    }
}
`

**Comment by abaglione** [comment] 2017-11-21 16:25
Same issue here =/ Builds and compiles fine, but doesn't display anything  / play anything. Heyyyyyy Spotify developers, any suggestions?

**Comment by hallyhaa** [comment] 2017-11-26 21:48
Even worse for me: the default example application compiles just fine, but when I run it on my Galaxy S8, the app craches almost immediately. Actually, it's the line in `onActivityResult` that begins with `Spotify.getPlayer( ...`
that crashes, because, according to the logcat:

> java.lang.NoSuchMethodError: no non-static method "Lcom/spotify/sdk/android/player/Config;.shouldUseCache()Z"


When tamering a bit with the code and adapting it to the rest of my app, in kotlin, it seems that the parent java object named `NativeObject` hasn't got a field called `nPtr`. And there's a long stack trace for native code.

Any suggestions?

**Comment by jarjarfinks** [comment] 2018-01-12 09:02
Any updates on this? I have the same problem

**Comment by bih** [comment] 2018-01-12 14:21
I created an official issue as #395 so we can keep track of all the issues with Quick Start and address them all. Please re-post your issue on there (if not, we have this referenced so we can investigate later too) but I'll close this issue as it is now a duplicate of that main ticket.

**Closed by bih** 2018-01-12 14:21 UTC
