### ISSUE TITLE
Crash caused by the Cache

### ISSUE THREAD

**Issue by Brad-Jackson** [spotify/android-sdk#224] opened 2016-05-05 04:07 UTC
This is not 100% re-producable, once a device starts having the problem it is consistent.

I have a Kiosk app that runs 24-7, that is logged into Spotify. When the problem starts occuring the app will carsh regularly. The problem is the app runs out of File Descriptors, once an Android app reaches 1024 open file descriptors; the app will be automatically closed.

I have made a temporary fix with the following code.

    Config playerConfig = new Config(mActivity.get().getApplicationContext(), aToken, CLIENT_ID);
    playerConfig.useCache(false);
    Player.Builder builder = new Player.Builder(playerConfig);

Can you look into this please, as I would like to use the cache.

**Comment by roberttaylor426** [comment] 2016-05-16 16:09
Duplicate of #183.

**Comment by d-kunin** [comment] 2016-07-14 15:24
That should be fixed since https://github.com/spotify/android-sdk/releases/tag/1.0.0-beta13

**Closed by d-kunin** 2016-07-14 15:24 UTC
Labels: crash, Streaming
