### ISSUE TITLE
Missing DemoActivity.xml and resources?

### ISSUE THREAD

**Issue by happyruss** [spotify/android-sdk#210] opened 2016-03-14 17:09 UTC
Hey, sorry if this is posted in the wrong place, but you guys are super-quick on responding, and I've had this question on stackoverflow for a few days with no response.

The sdk includes a file called "DemoActivity.js" but there is no corresponding XML for the resources, so this line of code fails to compile: import com.spotify.sdk.embedded.demo.R;

These refer to the various UI element objects such as

        R.id.skip_next_button,
        R.id.skip_prev_button,
        R.id.queue_song_button,
        R.id.toggle_shuffle_button,
        R.id.toggle_repeat_button

I have properly set my SDK references to the two aar files, so all of the other import references resolve properly, but not this one. Do we need to create our own XML for these? Also, what about the actual images that go there? What am i missing? Am I responsible to create all this stuff myself, or can you provide it so every developer doesn't have to reinvent the wheel and perhaps there might be some consistency across apps that use the API and start from the demo project if people use it?

**Comment by d-kunin** [comment] 2016-09-02 15:34
dupe of https://github.com/spotify/android-sdk/issues/269

**Closed by d-kunin** 2016-09-02 15:34 UTC
