### ISSUE TITLE
When the Spotify (Android) app is installed but the user is not logged in, nothing will 'open' when you try to authenticate Spotify (i.e. let the user login) with your app.

### ISSUE THREAD

**Issue by tom12e** [spotify/android-sdk#226] opened 2016-05-10 09:20 UTC

**Comment by sampurcell93** [comment] 2016-05-10 22:40
I noticed this too... Luckily, it seems like a pretty uncommon case, but it's been annoying for testing.

**Comment by roberttaylor426** [comment] 2016-05-16 15:20
Duplicate of #175.

**Comment by d-kunin** [comment] 2016-09-02 15:38
closing as dupe

**Closed by d-kunin** 2016-09-02 15:38 UTC
Labels: auth
