### ISSUE TITLE
java.util.concurrent.RejectedExecutionException: Player is shut down

### ISSUE THREAD

**Issue by Wolftein** [spotify/android-sdk#97] opened 2015-03-30 15:52 UTC
This happend sometimes:

```
java.util.concurrent.RejectedExecutionException: Player is shut down
at com.spotify.sdk.android.player.Player.checkForShutdown(UTone:585)
at com.spotify.sdk.android.player.Player.submit(UTone:574)
at com.spotify.sdk.android.player.Player.setPlaybackBitrate(UTone:1038)
at me.siegenthaler.utone.sp.SpProviderAPI.onInitialized(UTone:368)
at com.spotify.sdk.android.player.Player$2.run(UTone:398)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5099)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
at dalvik.system.NativeStart.main(Native Method)
```

I'm calling setPlaybackBitrate(..) inside onInitialized callback.

**Comment by kaaes** [comment] 2015-03-31 16:47
This looks to me like a concurrency issue. I'm guessing the player is shutdown but not completely terminated when `Spotify.getPlayer` gets called again.
I will check the code and see if we can improve the behaviour in such cases but to be on the safe side I'd suggest using `Spotify.awaitDestroyPlayer` method when destroying the player. This method is synchronous and will ensure that the player is completely destroyed before it is recreated.

**Comment by Wolftein** [comment] 2015-03-31 16:51
Yes, i'm already calling awaitDestroyPlayer before releasing the player.

```
        if (mPlayer != null) {
            Spotify.destroyPlayer(this);
        }
        try {
            Spotify.awaitDestroyPlayer(this, 5000L, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ignored) {
        }
```
I guess the player wasn't destroy within 5000 ms.

**Comment by kaaes** [comment] 2015-03-31 17:29
Could you check if this is indeed the case? It sounds quite unusual that the player would not be properly destroyed in 5s but I'd like to verify if this is the cause of RejectedExecutionException you're seeing.

**Comment by kaaes** [comment] 2015-04-23 09:33
@Wolftein I found the reason for this behaviour. I will fix it but you should also change your code to:
```java
if (mPlayer != null) {
    try {
       Spotify.awaitDestroyPlayer(this, 5000L, TimeUnit.MILLISECONDS);
    } catch (InterruptedException ignored) {}
}
```
Using both `destroy` and `awaitDestroy` results in synchronous call not doing its work as the player has been already shutdown and removed

**Comment by Wolftein** [comment] 2015-04-23 19:49
Will test it when the update is released, thanks.

**Comment by kaaes** [comment] 2015-04-28 08:14
This should be fixed now in 1.0.0-beta10

**Comment by kaaes** [comment] 2015-05-05 08:17
I'm going to close this. Please let us know if you run into this issue again

**Closed by kaaes** 2015-05-05 08:17 UTC
Labels: bug, next-release

**Comment by bimusiek** [comment] 2015-05-14 16:06
Hey, I am using
    
    // This library handles music playback
    compile 'com.spotify.sdk:spotify-player:1.0.0-beta10@aar'

However I am getting in constantly now when changing song.

	05-14 18:02:17.562    2585-2585/sharklist.it.sharklist E/AndroidRuntime﹕ FATAL EXCEPTION: main
	    Process: sharklist.it.sharklist, PID: 2585
	    java.util.concurrent.RejectedExecutionException: Player is shut down
	            at com.spotify.sdk.android.player.Player.checkForShutdown(Player.java:591)
	            at com.spotify.sdk.android.player.Player.submit(Player.java:580)
	            at com.spotify.sdk.android.player.Player.play(Player.java:831)
	            at sharklist.it.sharklist.views.PlayerActivity.setLocation(PlayerActivity.java:217)
	            at sharklist.it.sharklist.views.PlayerActivity$9.success(PlayerActivity.java:293)
	            at sharklist.it.sharklist.views.PlayerActivity$9.success(PlayerActivity.java:290)
	            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
	            at android.os.Handler.handleCallback(Handler.java:739)
	            at android.os.Handler.dispatchMessage(Handler.java:95)
	            at android.os.Looper.loop(Looper.java:135)
	            at android.app.ActivityThread.main(ActivityThread.java:5221)
	            at java.lang.reflect.Method.invoke(Native Method)
	            at java.lang.reflect.Method.invoke(Method.java:372)
	            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Any ideas? Player is already started for sure, and then i am just doing `mPlayer.play()`

**Comment by bimusiek** [comment] 2015-05-14 16:20
Way to reproduce is to create Activity with player. Then go back and in `onDestroy` do

        try {
            Spotify.awaitDestroyPlayer(this, 15000L, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ignored) {}

And then open this activity again, first song will play correctly. But next one will cause this exception to be thrown.

**Comment by bimusiek** [comment] 2015-05-14 16:49
Ok, investigating more I found root problem. I called `.play()` few times at once. However I think it should either queue it or disallow it with proper exception.

**Comment by kaaes** [comment] 2015-05-18 16:18
@bimusiek this exception is only thrown when trying to invoke the command on the player that is shut down. Please check if you're not trying to call `play` after destroying the player (Maybe in a callback?)

**Comment by bimusiek** [comment] 2015-05-18 16:20
@kaaes I checked few times, after callback that player is ready I did `.play(URI)` and then after few ms I did it again. 

My bad cause I switched next track with current track, then got response from backend with old data that swapped it again. So I tried to play 2 different tracks almost at once. 

I can try later to reproduce it and post source code.
