### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by hammar83** [spotify/android-sdk#174] opened 2016-01-07 09:24 UTC
Sometimes during authentication of user, the [com.spotify.sdk.android.authentication.LoginActivity] returns a error with error message "INTERNAL_ERROR". If I restart the application the auth flow works as normal and the user is authenticated.

Does anyone have a clue why this happens and how to prevent it?

**Comment by kaaes** [comment] 2016-01-08 11:18
@hammar83 thanks for the report, we'll look into this issue

**Comment by dcamp200** [comment] 2016-01-16 18:40
If it helps, I do have a couple of stack traces.  
The issue occurs the first time I start my app.  Exiting the app and restarting seems to work. 
Also after uninstalling the Spotify app I don't get the error (SSO related?)

Here is the extra stack trace that occurs when the error happens:
01-16 13:15:05.427 29394-29394/? E/Spotify: [main@sso.AuthorizationActivity$2:267] Bakery request failed
                                            com.spotify.mobile.android.cosmos.ParsingCallbackReceiver$ParserException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
                                             at [Source: [B@30b9c53c; line: 1, column: 1]
                                                at com.spotify.mobile.android.cosmos.parser.JsonParser.parseResponse(SourceFile:60)
                                                at com.spotify.mobile.android.cosmos.DelegableParsingCallbackReceiver.parseResponse(SourceFile:21)
                                                at com.spotify.mobile.android.cosmos.ParsingCallbackReceiver.onResolved(SourceFile:50)
                                                at com.spotify.cosmos.android.Resolver$CallbackReceiver.sendOnResolved(SourceFile:155)
                                                at com.spotify.cosmos.android.RemoteNativeRouter$SubscriptionResolveCallback.onResolved(SourceFile:55)
                                                at com.spotify.cosmos.android.RemoteNativeRouter$CancellingResolveCallback.onResolved(SourceFile:82)
                                                at com.spotify.cosmos.android.RemoteNativeRouter$WeakResolveCallbackWrapper.onResolved(SourceFile:264)
                                             Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
                                             at [Source: [B@30b9c53c; line: 1, column: 1]
                                                at com.fasterxml.jackson.databind.ObjectMapper._initForReading(SourceFile:3781)
                                                at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(SourceFile:3721)
                                                at com.fasterxml.jackson.databind.ObjectMapper.readValue(SourceFile:2819)
                                                at com.spotify.mobile.android.cosmos.parser.JsonParser.parseResponse(SourceFile:51)
                                                	... 6 more
01-16 13:15:05.437 29394-29394/? E/Spotify: [main@sso.AuthorizationActivity:372] INTERNAL_ERROR


I also have this stack trace even when it does work:

01-16 13:15:04.367 3641-4295/? E/Parcel: Class not found when unmarshalling: com.spotify.sdk.android.authentication.AuthenticationRequest
                                         java.lang.ClassNotFoundException: com.spotify.sdk.android.authentication.AuthenticationRequest
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:309)
                                             at java.lang.Class.forName(Class.java:273)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                             at android.os.Parcel.readParcelable(Parcel.java:2245)
                                             at android.os.Parcel.readValue(Parcel.java:2152)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:918)
                                             at android.content.Intent.getStringExtra(Intent.java:5767)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5844)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5628)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3821)
                                             at android.os.Binder.execTransact(Binder.java:461)
                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.spotify.sdk.android.authentication.AuthenticationRequest" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:309) 
                                             at java.lang.Class.forName(Class.java:273) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2281) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2245) 
                                             at android.os.Parcel.readValue(Parcel.java:2152) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2485) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:918) 
                                             at android.content.Intent.getStringExtra(Intent.java:5767) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2365) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1848) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5844) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5628) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:142) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3821) 
                                             at android.os.Binder.execTransact(Binder.java:461) 
                                         	Suppressed: java.lang.ClassNotFoundException: com.spotify.sdk.android.authentication.AuthenticationRequest
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by kaaes** [comment] 2016-02-05 13:02
This issue should not occur with Spotify version 4.6. I'll close it but please let us know if you see something wrong with the auth flow again

**Closed by kaaes** 2016-02-05 13:02 UTC
Labels: bug

**Comment by Brad-Jackson** [comment] 2016-03-29 22:28
When is this fix being released, I have beta 12 and it still is happening. I have several devices but it only seems to happen on the Samsung Tab A.
